version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - webnet

  frontend:
    build: ./social-network-frontend/social-network
    volumes:
      - ./social-network-frontend/social-network:/app
    ports:
      - "3000:3000"
    networks:
      - webnet

  backend:
    build: ./social-network-backend
    volumes:
      - ./social-network-backend:/app
    ports:
      - "3001:3001"
    networks:
      - webnet

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    networks:
      - webnet

networks:
  webnet:
