# Dockerfile pour le service Backend
FROM node:latest

# Créer le répertoire de l'application
WORKDIR /usr/src/app

# Installer les dépendances de l'application
COPY package*.json ./

RUN npm install 

# Copier le code source de l'application
COPY . .

# Construire l'application
RUN npm run build

# Exposer le port sur lequel l'application fonctionne
EXPOSE 3000

# Commande pour exécuter l'application
CMD [ "node", "dist/index.js" ]


#Ce fichier Dockerfile construit une image Docker pour le service backend en installant les dépendances, en copiant le code source, en construisant l'application et en définissant la commande pour exécuter l'application.