---
- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

- hosts: manager
  become: yes
  tasks:
    - name: Initialize Docker Swarm
      shell: docker swarm init --advertise-addr {{ ansible_host }}
      register: swarm_init
      failed_when: "'Error response' in swarm_init.stderr"

    - name: Get Docker Swarm join token
      shell: docker swarm join-token worker -q
      register: join_token

- hosts: workers
  become: yes
  tasks:
    - name: Join Docker Swarm
      shell: docker swarm join --token {{ hostvars['manager'].join_token.stdout }} {{ hostvars['manager'].ansible_host }}:2377
      register: join_result
      failed_when: "'Error response' in join_result.stderr"
